### ISSUE TITLE
Example for WFC3 gives an error

### ISSUE THREAD

**Issue by karllark** [spacetelescope/ABSCAL#23]
## Describe the bug / feature

  
         
         
         
  
  
  
  

  
  

Ran the WFC3 grism example using the [instructions](https://abscal.readthedocs.io/en/latest/abscal_examples/wfc3.html).  The `wfc3_setup` command worked.  The `wfc3_coadd` command produced this output:

```
(abscal) kgordon@beast GD153]$ wfc3_coadd -fvdt dirtemp_grism.log
Traceback (most recent call last):
  File "/user/kgordon/anaconda3/envs/abscal/bin/wfc3_coadd", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/commands/wfc3_coadd", line 25, in <module>
    main()
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/commands/wfc3_coadd", line 21, in main
    do_coadd(**kwargs)
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/wfc3/reduce_grism_coadd.py", line 878, in main
    parsed = parse_args(**kwargs)
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/wfc3/reduce_grism_coadd.py", line 842, in parse_args
    extracted_args = extract_args()
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/wfc3/reduce_grism_extract.py", line 2315, in additional_args
    'default': base_defaults['plots'], 'help': trace_help}
NameError: name 'trace_help' is not defined. Did you mean: 'table_help'?
````
I got the the same error when I tried to get help for this command by running `wfc3_coadd --help`.

**Comment by karllark** [comment]
With the latest version, I get a different error.

```
(abscal) kgordon@beast GD153]$ wfc3_coadd -fvdt dirtemp_grism.log
usage: wfc3_coadd [-h] [--paths PATHS] [-i IN_FILE] [-o OUT_FILE]
                  [-s SPEC_DIR] [-c] [-f] [-v] [-d] [--prefix PREFIX] [-p]
                  [-b BKG_FLAT_ORDER]
                  table
wfc3_coadd: error: argument -d/--double: ignored explicit argument 't'
```

**Comment by karllark** [comment]
When running `wfc3_coadd --help` there is no indication that `t` is a valid command line switch.  Removing it results in the following error.

```
(abscal) kgordon@beast GD153]$ wfc3_coadd -fvd dirtemp_grism.log
{'paths': ['/user/kgordon/Hubble/ABSCAL/WFC3/GD153'], 'in_file': None, 'out_file': 'dirirstare.log', 'spec_dir': 'spec', 'compat': False, 'force': True, 'verbose': True, 'table': 'dirtemp_grism.log', 'double': True, 'prefix': None, 'plots': False, 'bkg_flat_order': 'flat_first'}
wfc3: grism: coadd: Starting WFC3 coadd for GRISM data.
wfc3: grism: coadd: Input table is:
   root   obset  ... planetary_nebula                            notes                           
--------- ------ ... ---------------- -----------------------------------------------------------
idvj01p4q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01p5q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01p7q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01p8q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01paq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01pbq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01phq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01piq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01pkq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01plq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01poq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01ppq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
wfc3: grism: coadd: Found 1 unique obsets: ['idvj01']
Traceback (most recent call last):
  File "/user/kgordon/anaconda3/envs/abscal/bin/wfc3_coadd", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/commands/wfc3_coadd", line 25, in <module>
    main()
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/commands/wfc3_coadd", line 21, in main
    do_coadd(**kwargs)
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/wfc3/reduce_grism_coadd.py", line 889, in main
    output_table = coadd(input_table, **vars(parsed), **kwargs)
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/wfc3/reduce_grism_coadd.py", line 168, in coadd
    if os.path.isfile(os.path.join(out_dir, filter_table[0]['coadded'])):
  File "/user/kgordon/anaconda3/envs/abscal/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/user/kgordon/anaconda3/envs/abscal/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'MaskedConstant'
```

**Comment by karllark** [comment]
Getting further with the latest update.

```
(abscal) kgordon@beast GD153]$ wfc3_coadd -fvd dirtemp_grism.log
{'paths': ['/user/kgordon/Hubble/ABSCAL/WFC3/GD153'], 'in_file': None, 'out_file': 'dirirstare.log', 'spec_dir': 'spec', 'compat': False, 'force': True, 'verbose': True, 'table': 'dirtemp_grism.log', 'double': True, 'prefix': None, 'plots': False, 'bkg_flat_order': 'flat_first'}
wfc3: grism: coadd: Starting WFC3 coadd for GRISM data.
wfc3: grism: coadd: Input table is:
   root   obset  ... planetary_nebula                            notes                           
--------- ------ ... ---------------- -----------------------------------------------------------
idvj01p4q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01p5q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01p7q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01p8q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01paq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01pbq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01phq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01piq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01pkq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01plq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01poq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01ppq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
wfc3: grism: coadd: Found 1 unique obsets: ['idvj01']
wfc3: grism: coadd: Co-adding idvj01
wfc3: grism: coadd: idvj01 table for G102 is:
   root   obset  ... planetary_nebula                            notes                           
--------- ------ ... ---------------- -----------------------------------------------------------
idvj01p5q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01p8q idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
idvj01pbq idvj01 ...            False {}: Could not find SPT file for {}. Setting scan rate to 0.
Traceback (most recent call last):
  File "/user/kgordon/anaconda3/envs/abscal/bin/wfc3_coadd", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/commands/wfc3_coadd", line 25, in <module>
    main()
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/commands/wfc3_coadd", line 21, in main
    do_coadd(**kwargs)
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/wfc3/reduce_grism_coadd.py", line 891, in main
    output_table = coadd(input_table, **vars(parsed), **kwargs)
  File "/user/kgordon/STScI/AbsFlux/ABSCAL/abscal/wfc3/reduce_grism_coadd.py", line 216, in coadd
    spec_file = os.path.join(row['path'], row['extracted'])
  File "/user/kgordon/anaconda3/envs/abscal/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/user/kgordon/anaconda3/envs/abscal/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'MaskedConstant'

```

**Comment by karllark** [comment]
With all the updates, the example now works!  Closing this issue.
